### ISSUE TITLE
[Feature Request] Disabling Console messages via config

### ISSUE THREAD

**Issue by KadTheHunter** [tgwaste/Weather#3]
Having an option to disable console messages via config would be great, as it gets rather spammy.
By console messages, I mean the messages saying `Weather is <Weather> <Length in Seconds>`.

(Sorry for the edits, my laptop was lagging and I accidentally submitted the issue before it was typed lmao)

**Comment by tgwaste** [comment]
v1.0.3 just released has this.

**Comment by KadTheHunter** [comment]
Thanks :)
