### ISSUE TITLE
TypeError: "pocketmine\math\Vector3::__construct(): Argument #2 ($y) must be of type int|float, null given.

### ISSUE THREAD

**Issue by edwinyoo44** [tgwaste/Weather#4]
`
2022-03-05 [21:40:55.005] [Server thread/CRITICAL]: TypeError: "pocketmine\math\Vector3::__construct(): Argument #2 ($y) must be of type int|float, null given, called in phar:///home/edwinyoo44/MinecraftBEServer/pmmp/plugins/Weather_dev-6.phar/src/tgwaste/Weather/Weather.php on line 159" (EXCEPTION) in "pmsrc/vendor/pocketmine/math/src/Vector3" at line 41

--- Stack trace ---
  #0 plugins/Weather_dev-6.phar/src/tgwaste/Weather/Weather(159): pocketmine\math\Vector3->__construct(integer 5483, NULL , integer -2124)
  #1 plugins/Weather_dev-6.phar/src/tgwaste/Weather/Schedule(15): tgwaste\Weather\Weather->sendLightning()
  #2 pmsrc/src/scheduler/TaskHandler(117): tgwaste\Weather\Schedule->onRun()
  #3 pmsrc/src/scheduler/TaskScheduler(141): pocketmine\scheduler\TaskHandler->run()
  #4 pmsrc/src/plugin/PluginManager(466): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 43381)
  #5 pmsrc/src/Server(1768): pocketmine\plugin\PluginManager->tickSchedulers(integer 43381)
  #6 pmsrc/src/Server(1657): pocketmine\Server->tick()
  #7 pmsrc/src/Server(1046): pocketmine\Server->tickProcessor()
  #8 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#2, string[40] /home/edwinyoo44/MinecraftBEServer/pmmp/, string[48] /home/edwinyoo44/MinecraftBEServer/pmmp/plugins/)
  #9 pmsrc/src/PocketMine(327): pocketmine\server()
  #10 pmsrc(11): require(string[90] phar:///home/edwinyoo44/MinecraftBEServer/pmmp/PocketMine-MP_4.2.2.phar/src/Pock)
--- End of exception information ---
`

**Comment by tgwaste** [comment]
Weather_dev-6.phar is not my .phar.

**Comment by tgwaste** [comment]
oh...
grrrrrrrr
PocketMine-MP/changelogs/4.0.md:  - `World->getHighestBlockAt()` now returns `null` instead of `-1` if the target X/Z column contains no blocks.

**Comment by edwinyoo44** [comment]
> 

Download from here
https://poggit.pmmp.io/ci/tgwaste/Weather/Weather/dev:6

**Comment by tgwaste** [comment]
fix
[Weather.phar.zip](https://github.com/tgwaste/Weather/files/8191087/Weather.phar.zip)
