### ISSUE TITLE
Argument  support `[duration: int]` 

### ISSUE THREAD

**Issue by NhanAZ** [tgwaste/Weather#8]
something like `/weather rain [duration: int]`
You can refer to `[duration: int]` argument in vanilla Minecraft, I took the idea from that to create this issues.
If the `[duration: int]` argument is not provided, the time will be random

**Comment by NhanAZ** [comment]
By the way, why `/weather status` instead of `/weather query` like vanilla Minecraft. It would be great if it was re-edited.

**Comment by tgwaste** [comment]
added duration
changed status to query, but status still works as well.
